### ISSUE TITLE
Can't locate object method "subtest" via package "Test::Builder"

### ISSUE THREAD

**Issue by andreashe** [doherty/String-Trim#1]
Can't locate object method "subtest" via package "Test::Builder"

Maybe my perl is old, but such a simple class should also run with older perl.

**Comment by doherty** [comment]
Thank you for reporting this bug. A minimum version of Test::More is required to use the subtest feature, but I don't recall offhand what version that is. Could you please report what version of Test::More you're using?

**Comment by doherty** [comment]
Please also report the test suite's output.

The relevant tests do require Test::More 0.94, which appears to be correct. If you don't have that minimum version, the tests should fail to run entirely - though if you are using the CPAN.pm shell (or any similar tool), you should be offered the option to upgrade. Please verify your installation meets the minimum requirements before attempting to install.

**Comment by andreashe** [comment]
Ive got 0.94

BTW: your Lingua::Boolean file for download is broken. When extracting it, all files are in main folder. imho it has also too many dependencies for such a simple tool. Lingua::Boolean is what I realy need, but it wants Trim.

**Comment by doherty** [comment]
Okay, please show me  your build and test output.

I'll file a bug for you against Lingua::Boolean.

**Comment by andreashe** [comment]
# cpanm String::Trim

--> Working on String::Trim
Fetching http://search.cpan.org/CPAN/authors/id/D/DO/DOHERTY/String-Trim-0.002.tar.gz ... OK
Configuring String-Trim-0.002 ... OK
Building and testing String-Trim-0.002 ... FAIL
! Installing String::Trim failed. See /root/.cpanm/build.log for details.

---

--> Working on String::Trim  
Fetching http://search.cpan.org/CPAN/authors/id/D/DO/DOHERTY/String-Trim-0.002.tar.gz
-> OK  
Unpacking String-Trim-0.002.tar.gz  
Entering String-Trim-0.002  
Checking if you have ExtUtils::MakeMaker 6.31 ... Yes (6.56)  
Configuring String-Trim-0.002  
Running Makefile.PL  
Checking if your kit is complete...  
Looks good  
Writing Makefile for String::Trim  
-> OK  
Finding PREREQ from Makefile ...  
Checking if you have Test::More 0.94 ... Yes (0.94)  
Checking if you have File::Find 0 ... Yes (1.12)  
Checking if you have File::Temp 0 ... Yes (0.22)  
Checking if you have Exporter 0 ... Yes (5.63)  
Building and testing String-Trim-0.002  
cp lib/String/Trim.pm blib/lib/String/Trim.pm  
Manifying blib/man3/String::Trim.3pm  
PERL_DL_NONLAZY=1 /usr/bin/perl "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-compile.t ... ok
t/00-use.t ....... ok
Can't locate object method "subtest" via package "Test::Builder" at /usr/share/perl/5.10/Test/More.pm line 725.

# Looks like your test exited with 255 before it could output anything.

t/01-string.t ....
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/2 subtests
Can't locate object method "subtest" via package "Test::Builder" at /usr/share/perl/5.10/Test/More.pm line 725.

# Looks like your test exited with 255 before it could output anything.

t/02-undef.t .....
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/2 subtests
Can't locate object method "subtest" via package "Test::Builder" at /usr/share/perl/5.10/Test/More.pm line 725.

# Looks like your test exited with 255 before it could output anything.

t/03-array.t .....
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/2 subtests
Can't locate object method "subtest" via package "Test::Builder" at /usr/share/perl/5.10/Test/More.pm line 725.

# Looks like your test exited with 255 before it could output anything.

t/04-arrayref.t ..
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 2/2 subtests

## Test Summary Report

t/01-string.t  (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 2 tests but ran 0.
t/02-undef.t   (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 2 tests but ran 0.
t/03-array.t   (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 2 tests but ran 0.
t/04-arrayref.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 2 tests but ran 0.
Files=6, Tests=2,  1 wallclock secs ( 0.02 usr  0.00 sys +  0.17 cusr  0.02 csys =  0.21 CPU)
Result: FAIL
Failed 4/6 test programs. 0/2 subtests failed.
make: **\* [test_dynamic] Fehler 255
-> FAIL Installing String::Trim failed. See /root/.cpanm/build.log for details.

**Comment by doherty** [comment]
Thank you. Would you please report your Test::Builder version number? I think it /should/ be 0.94 as well.

This is a bit tiresome though - perhaps I'll rewrite the test suite without subtest...

**Comment by doherty** [comment]
BTW, your Lingua::Boolean bug is [over there](https://github.com/doherty/Lingua-Boolean/issues#issue/2) & I need to know which download you're referring to.

**Comment by andreashe** [comment]
Test::Builder
0.86

I use allways cpanm which goes e.g. to  http://search.cpan.org/CPAN/authors/id/D/DO/DOHERTY/String-Trim-0.002.tar.gz

**Comment by doherty** [comment]
Okay, please upgrade to Test::Builder 0.94 as well. I was under the impression that requiring Test::More 0.94 implied also requiring Test::Builder 0.94. I will include this requirement in the next release (unless I rewrite the tests to not use subtest).

**Comment by andreashe** [comment]
it works now:

Fetching http://search.cpan.org/CPAN/authors/id/D/DO/DOHERTY/String-Trim-0.002.tar.gz ... OK
Configuring String-Trim-0.002 ... OK
Building and testing String-Trim-0.002 ... OK
Successfully installed String-Trim-0.002

But Lingua-Boolean is still not possible. Ive got also:

perl, v5.10.0

**Comment by doherty** [comment]
Thank you. Please file a bug against Lingua::Boolean if you have still have trouble with that module. I'll fix this bug and release a new version to the CPAN later today.

**Comment by doherty** [comment]
Fixed by SHA: 8cb0e2d3d070824b4b1ee0edf8cd2272bf67d591
